[project]
authors = ["Alex Kreidler <alex.contributing@alexkreidler.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "libcloud"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
apache-libcloud = ">=3.8.0,<4"
toml = ">=0.10.2,<0.11"
orjson = ">=3.10.11,<4"
jsonpickle = ">=4.0.0,<5"
pandas = ">=2.2.3,<3"
black = ">=24.10.0,<25"
matplotlib = ">=3.9.2,<4"
